### ISSUE TITLE
Não versionar `vendor`

### ISSUE THREAD

**Issue by augustohp** [dinhooliveira/correios#1]
O diretório `vendor` têm as dependências instaladas pelo Composer, a ideia é que elas sejam mantidas pelo `composer.json` e pelo `composer.lock`. Por ser uma biblioteca, o `composer.lock` é ignorado quando utilizado em uma outra aplicação que irá utilizar o próprio `composer.lock` existente nela.

Normalmente colocamos o diretório `vendor` no `.gitignore` para impedir que arquivos neste diretório sejam adicionados no Git (versionamento de código), já que eles já são versionados nos repositórios de cada biblioteca e controlados pelo Composer. O Composer existe justamente pra não precisamos incluir código que não é do nosso projeto.

Sugiro 2 mudanças:

* [x] Incluir `vendor` no `.gitignore`
* [x] Remover diretório `vendor` do repositório

**Comment by dinhooliveira** [comment]
Feito obrigado pela observação.
